# +--------------------------------------------------------------------------+ #
# <                    MagmaBuildNetwork Configuration File                  > #
# <--------------------------------------------------------------------------> #
# <               For help understanding a config option go to               > #
# <          https://github.com/FourteenBrush/FourteenBrush.github.io        > #
# <                  or Discord https://discord.gg/KWNYMDGX7H                > #
# +--------------------------------------------------------------------------+ #


# +--------------------------------------------------------------------------+ #
# TRADE DATA
# This section stores data about the /trade command

# Max distance between two players to make them able to accept the trade (in blocks)
max_trade_distance: 20
# Make players able to trade in different worlds (for example the nether and the overworld)
trade_from_different_worlds: false

# +--------------------------------------------------------------------------+ #
# DEPENDENCIES
# This section stores data about dependencies like Vault and PlaceholderAPI

# Does this plugin requires this plugins in order to function
# Note: only change this to true when you want to use one of their features
requires_vault: false
requires_placeholderAPI: false
requires_luckperms: false

# +--------------------------------------------------------------------------+ #
# SCOREBOARD
# This section stores data about the scoreboard ingame

# Do you want to use the scoreboard
# NOTE: this will override all the scoreboards
use_scoreboard: true
# Configure the scoreboard layout
scoreboards:
  1:
    enabled: true
    title: ""
    scores:
      13:
        - ""
      12:
        - ""
      11:
        - ""
      10:
        - ""
      9:
        - ""
      8:
        - ""
      7:
        - ""
      6:
        - ""
      5:
        - ""
      4:
        - ""
      3:
        - ""
      2:
        - ""
      1:
        - ""

# +--------------------------------------------------------------------------+ #
# NPC DATA
# This section stores data about NPCs and is generated by the plugin itself
npc_data:

