# +--------------------------------------------------------------------------+ #
# <                    MagmaBuildNetwork Configuration File                  > #
# <--------------------------------------------------------------------------> #
# <               For help understanding a config option go to               > #
# <          https://github.com/FourteenBrush/FourteenBrush.github.io        > #
# <                  or Discord https://discord.gg/KWNYMDGX7H                > #
# +--------------------------------------------------------------------------+ #


# +--------------------------------------------------------------------------+ #
# TRADE DATA
# This section stores data about the /trade command

# Max distance between two players to make them able to accept the trade (in blocks)
max_trade_distance: 20
# Are players able to trade in different worlds (for example the nether and the overworld)
trade_from_different_worlds: false

# +--------------------------------------------------------------------------+ #
# VANISH
# This section stores config options about about the vanish command

# Are players in vanish able to pickup items
pickup_items_during_vanish: false
# Do players in vanish get the nightvision effect
nightvision_during_vanish: true
# Disable hunger in vanish
disable_hunger_in_vanish: true

# +--------------------------------------------------------------------------+ #
# SPAWN
# This section stores config options for the spawn command

teleport_to_spawn_on:
  first_join: true
  join: false
  respawn: true
disable_spawn_command_in_pvp: true
spawn:
  world:
  x:
  y:
  z:
  yaw:
  pitch:

# +--------------------------------------------------------------------------+ #
# DEPENDENCIES
# This section stores config options about dependencies like Vault and PlaceholderAPI

# Does this plugin requires this plugins in order to function
# Note: only change this to true when you want to use one of their features
requires_vault: false
requires_placeholderAPI: false
requires_luckperms: false

# +--------------------------------------------------------------------------+ #
# SCOREBOARD
# This section stores data about the scoreboard ingame

# Do you want to use the scoreboard
# NOTE: this will override all the scoreboards
use_scoreboard: true
# Configure the scoreboard layout
scoreboards:
  1:
    enabled: true
    title: ""
    scores:
      13:
        - ""
      12:
        - ""
      11:
        - ""
      10:
        - ""
      9:
        - ""
      8:
        - ""
      7:
        - ""
      6:
        - ""
      5:
        - ""
      4:
        - ""
      3:
        - ""
      2:
        - ""
      1:
        - ""

# +--------------------------------------------------------------------------+ #
# NPC DATA
# This section stores data about NPCs and is generated by the plugin itself
npc_data:

