name: MagmaBuildNetwork
version: 1.0
author: FourteenBrush
main: io.github.FourteenBrush.MagmaBuildNetwork.Main
api-version: 1.13
softdepend: [LuckPerms, PlaceHolderAPI, Vault]

commands:
  magmabuildnetwork:
    description: Main command
    aliases: [mbn]
  reload:
    description: Reloads the plugin
    permission: <plugin name>.reload
  ignite:
    description: Sets a player on fire
    permission: <plugin name>.ignite
  freeze:
    description: Freezes a player
    permission: <plugin name>.freeze
  heal:
    description: Heals a player
    permission: <plugin name>.heal
  lock:
    description: Allows you to protect a container
    permission: <plugin name>.basic
  store:
    description: Stores a message inside the NBT tags of an item
    permission: <plugin name>.store
  stats:
    description: Shows player stats
    permission: <plugin name>.basic
  debug:
    description: Shows debug info
  trade:
    description: Sends a trade request to a player
  spawnnpc:
    description: Spawns an NPC
  trails:
    description: Shows all available trails
  createmap:
    description: Creates a custom Minecraft Map from an image
  console:
    description: Console command

permissions:
 magmabuildnetwork.admin:
    description: Grants access to all the commands
    default: false
    children:
     - magmabuildnetwork.reload
     - magmabuildnetwork.ignite
     - magmabuildnetwork.freeze
     - magmabuildnetwork.heal
     - magmabuildnetwork.store
     - magmabuildnetwork.basic
magmabuildnetwork.basic:
    description: Grants access to all player commands
    default: true