# +--------------------------------------------------------------------------+ #
# <                    MagmaBuildNetwork Configuration File                  > #
# <--------------------------------------------------------------------------> #
# <               For help understanding a config option go to               > #
# <          https://github.com/FourteenBrush/FourteenBrush.github.io        > #
# <                  or Discord https://discord.gg/KWNYMDGX7H                > #
# +--------------------------------------------------------------------------+ #

# Use MySQL as database, will use SQLite if false
use-mysql: false
# MySQL credentials if use-mysql is set to true
mysql:
  name: "minecraft"
  host: "localhost"
  port: 3306
  username: "mc"
  password: "password"

# Use this format to send messages to the chat
default-chat-format: "&7{CHANNEL_PREFIX} &7{PREFIX} {NAME} {SUFFIX} &7>> {MESSAGE}"
private-message-format: "&7{SENDER_PREFIX} {SENDER} &7>> {RECEIVER_PREFIX} {RECEIVER}:&7 {MESSAGE}"
# How often in milliseconds can a player send a message
rate-limit: 800

channels:
  global:
    prefix: "[&aGLOBAL]"
  local:
    prefix: "[L]"
    range: 50

trade:
  # Max distance in blocks between two players to make them able to trade
  # Set to -1 to disable
  max-distance: 20
  # Allow trading in creative game-mode
  allow-creative: true
  # Allow trading from different worlds, for example the nether and the end
  allow-from-different-worlds: false

# Allow players to pickup items during vanish
pickup-items-in-vanish: false
# Give players night-vision during vanish
nightvision-in-vanish: true
# Disable hunger during vanish
disable-hunger-in-vanish: true

teleport-to-spawn-on:
  first-join: true
  join: false
  respawn: true
disable-spawn-command-in-pvp: true
# The spawn location is set in the data.yml file

server-mode: maintenance