name: MagmaBuildNetwork
version: 1.0
author: FourteenBrush
main: io.github.FourteenBrush.MagmaBuildNetwork.MBNPlugin
api-version: 1.13
softdepend: [LuckPerms, PlaceHolderAPI, Vault, Essentials]

commands:
  magmabuildnetwork:
    description: Root command
    permission: magmabuildnetwork.admin
    aliases: [mbn]
  debug:
    description: For test purposes
    permission: magmabuildnetwork.admin
  freeze:
    description: Freezes a player
    permission: magmabuildnetwork.admin
  heal:
    description: Heals a player
    permission: magmabuildnetwork.admin
  vanish:
    description: Vanish command
    permission: magmabuildnetwork.admin
    aliases: [v]
  ban:
    description: Bans a player
    permission: magmabuildnetwork.admin
  fly:
    description: Allows a player to fly
    permission: magmabuildnetwork.admin
  maintenance:
    description: Enables server maintenance
  lock:
    description: Allows you to protect a container
    permission: magmabuildnetwork.basic
  stats:
    description: Shows player stats
    permission: magmabuildnetwork.basic
  trade:
    description: Sends a trade request to a player
    permission: magmabuildnetwork.basic
  trails:
    description: Shows all available trails
    permission: magmabuildnetwork.trails
  ally:
    description: Shows up ally menu
    permission: magmabuildnetwork.basic
  spawn:
    description: Teleports you to spawn
    permission: magmabuildnetwork.basic
  prefix:
    description: Shows up a prefix menu
    permission: magmabuildnetwork.basic
  shop:
    description: Shop command
    permission: magmabuildnetwork.basic
  home:
    description: Sets a home
    permission: magmabuildnetwork.basic
  tell:
    description: Sends a private message to a player
    permission: magmabuildnetwork.moderator
    aliases: [msg, pm, tell]
  reply:
    description: Replies to a conversation
    permission: magmabuildnetwork.moderator
    aliases: [r, re]
  chatchannel:
    description: Chatchannel options
    permission: magmabuildnetwork.basic
    aliases: [channel, ch]
  chat:
    description: Chat options
    permission: magmabuildnetwork.moderator
  safechest:
    description: Opens your safechest
    permission: magmabuildnetwork.safechest

permissions:
 magmabuildnetwork.admin:
    description: Grants access to all the commands
    default: op
    children:
     - magmabuildnetwork.basic
     - magmabuildnetwork.trails
     - magmabuildnetwork.safechest
     - magmabuildnetwork.notifyupdate
     - magmabuildnetwork.maintenance-bypass
     - magmabuildnetwork.moderator
 magmabuildnetwork.moderator:
   description: Moderator permission
   default: false
 magmabuildnetwork.notifyupdate:
   description: Notifies user of new version
   default: op
 magmabuildnetwork.maintenance-bypass:
   description: Bypasses the server maintenance launched by this plugin
   default: op
 magmabuildnetwork.basic:
    description: Grants access to all player commands
    default: true