name: MagmaBuildNetwork
version: 1.0
author: FourteenBrush
main: io.github.FourteenBrush.MagmaBuildNetwork.Main
api-version: 1.13
softdepend: [LuckPerms, PlaceHolderAPI, Vault, WorldGuard, EssentialsX]

commands:
  magmabuildnetwork:
    description: Root command
    permission: magmabuildnetwork.basic
    aliases: [mbn]
  debug:
    description: For test purposes
    permission: magmabuildnetwork.admin
  freeze:
    description: Freezes a player
    permission: magmabuildnetwork.admin
  heal:
    description: Heals a player
    permission: magmabuildnetwork.admin
  ignite:
    description: Sets a player on fire
    permission: magmabuildnetwork.admin
  store:
    description: Stores a message inside the NBT tags of an item
    permission: magmabuildnetwork.admin
  spawnnpc:
    description: Spawns an NPC
    permission: magmabuildnetwork.admin
  createmap:
    description: Creates a custom Minecraft Map from an image
    permission: magmabuildnetwork.admin
  vanish:
    description: Vanish command
    permission: magmabuildnetwork.vanish
  invsee:
    description: Shows the target's inventory
    permission: magmabuildnetwork.admin
  ban:
    description: Bans a player
    permission: magmabuildnetwork.admin
  lock:
    description: Allows you to protect a container
    permission: magmabuildnetwork.basic
  stats:
    description: Shows player stats
    permission: magmabuildnetwork.basic
  trade:
    description: Sends a trade request to a player
    permission: magmabuildnetwork.basic
  trails:
    description: Shows all available trails
    permission: magmabuildnetwork.trails
  ally:
    description: Shows up ally menu
    permission: magmabuildnetwork.basic
  spawn:
    description: Teleports you to spawn
    permission: magmabuildnetwork.basic
  prefix:
    description: Shows up a prefix menu
    permission: magmabuildnetwork.basic
  shop:
    description: Shop command
    permission: magmabuildnetwork.basic
  home:
    description: Sets a home
    permission: magmabuildnetwork.basic
  safechest:
    description: Opens your safechest
    permission: magmabuildnetwork.safechest

permissions:
 magmabuildnetwork.admin:
    description: Grants access to all the commands
    default: op
    children:
     - magmabuildnetwork.vanish
     - magmabuildnetwork.basic
     - magmabuildnetwork.safechest
     - magmabuildnetwork.notifyupdate
 magmabuildnetwork.notifyupdate:
   description: Notifies user of new version
   default: op
 magmabuildnetwork.basic:
    description: Grants access to all player commands
    default: true